### ISSUE TITLE
merge k8s-cloudkms-plugin/plugin/test_config.go into plugin_test.go

### ISSUE THREAD

**Issue by awly** [GoogleCloudPlatform/k8s-cloudkms-plugin#10]
Currently test_config.go is exposed to non-test code and is included in final binary
Move it to plugin_test.go since it's test-specific data.

**Comment by immutableT** [comment]
Created tests package and moved test_config.to into it. Eventually, plan to migrate all tests into this package to avoid similar issues.

**Comment by awly** [comment]
Hmm, not sure how creating a new package helps.
As long as you put the code into _test.go files, it's not included in final binary, only in test binary.

I recommend keeping contents of test_config.go in plugin/ directory

**Comment by immutableT** [comment]
Done.
