### ISSUE TITLE
Deployment instructions

### ISSUE THREAD

**Issue by niven01** [GoogleCloudPlatform/k8s-cloudkms-plugin#11]
Hi, 

As per https://github.com/kubernetes/features/issues/460#issuecomment-377276462 I was hoping some deployment instructions would be made available 

Any news on this?

**Comment by chhhavi** [comment]
We are also interested in getting some deployment instructions.

**Comment by sethvargo** [comment]
We've added deployment steps and guides in the README now: https://github.com/GoogleCloudPlatform/k8s-cloudkms-plugin#deploy-the-kms-plugin
