### ISSUE TITLE
required package (gopkg.in/gcfg.v1) not vendored

### ISSUE THREAD

**Issue by vineet-garg** [GoogleCloudPlatform/k8s-cloudkms-plugin#13]
The package is imported in
https://github.com/GoogleCloudPlatform/k8s-cloudkms-plugin/blob/master/plugin/http_client.go#L33

error during build:

[opc@instance-iad k8s-cloudkms-plugin]$ make
rm -f k8s-cloud-kms-plugin
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go test ./...
plugin/http_client.go:33:2: cannot find package "gopkg.in/gcfg.v1" in any of:
	/home/opc/go/src/github.com/GoogleCloudPlatform/k8s-cloudkms-plugin/vendor/gopkg.in/gcfg.v1 (vendor tree)
	/usr/local/go/src/gopkg.in/gcfg.v1 (from $GOROOT)
	/home/opc/go/src/gopkg.in/gcfg.v1 (from $GOPATH)
make: *** [build] Error 1

**Comment by sethvargo** [comment]
This is fixed and we've migrated to gomodules now 😄
