### ISSUE TITLE
"/k8s-cloud-kms-plugin not found"

### ISSUE THREAD

**Issue by huang-jy** [GoogleCloudPlatform/k8s-cloudkms-plugin#16]
Following the example on the main documentation, references the pre-built image `gcr.io/cloud-kms-lab/cloud-kms-plugin:dev`

When running the image using the example code:

```
docker run \
    --name="kms-plugin" \
    --network="host" \
    --detach \
    --rm \
    --volume "${SOCKET_DIR}:${SOCKET_DIR}:rw" \
    "${PLUGIN_IMAGE}" \
      /k8s-cloud-kms-plugin \
        --logtostderr \
        --integration-test="true" \
        --path-to-unix-socket="${SOCKET_PATH}" \
        --key-uri="${KMS_FULL_KEY}"
```

(with the variables set accordingly), docker throws out this error:

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/k8s-cloud-kms-plugin\": stat /k8s-cloud-kms-plugin: no such file or directory": unknown.`

I'm assuming this isn't intentional? Rebuilding the image using the guide also gives the same error using the newly built image.

**Comment by sethvargo** [comment]
Use `:0.1` instead of `:dev` for now

**Comment by murbano83** [comment]
hello @sethvargo , any news on this? The project it's discontinued?

Thanks!

**Comment by sethvargo** [comment]
Hi @murbano83 no, the project is not discontinued. If you're running on GKE, you can use this without installing the plugin now. See [Application-layer Encryption on GKE](https://cloud.google.com/kubernetes-engine/docs/how-to/encrypting-secrets).

**Comment by sethvargo** [comment]
Hi @murbano83 - I just pushed some updates and the container image will be kept in sync now.
