### ISSUE TITLE
service.proto missing

### ISSUE THREAD

**Issue by awly** [GoogleCloudPlatform/k8s-cloudkms-plugin#2]
https://github.com/GoogleCloudPlatform/k8s-cloudkms-plugin/tree/master/v1beta1 has the compiled Go proto stub, but not the `.proto` file itself.

**Comment by immutableT** [comment]
Done. 
Question: both proto and gen files are copied from k8s repo - this is the interface of KMS Plugin.
Is there a more elegant way to point to these files, as opposed to copying them.

**Comment by awly** [comment]
Is this the file you copied? https://github.com/kubernetes/kubernetes/blob/e40ffd71972b820aeed283946e880aa2479f8524/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/v1beta1/service.pb.go

You should be able to vendor it

**Comment by immutableT** [comment]
I was actually wanted to achieve something different - when K8S changes that file/interface, I want my tests to fail - forcing me to keep my plugin in sync with changes in K8S.

**Comment by awly** [comment]
You'll have to manually update the version you use in either case.
You could use some symlink magic, but that relies on you having an up-to-date copy of k8s locally.

**Comment by awly** [comment]
I think submodules still store a fixed version of a repo and need to be
manually updated.

**Comment by immutableT** [comment]
Yes, but I could include the required git commands in my make file - need to play with this more.

**Comment by awly** [comment]
You could also include the required dep commands

**Comment by immutableT** [comment]
Right.
