### ISSUE TITLE
Package plugin exports identifiers unnecessarily

### ISSUE THREAD

**Issue by awly** [GoogleCloudPlatform/k8s-cloudkms-plugin#5]
The only identifiers used in main are:
- MetricsPort/Path
- HealthzPort/Path
- New
- NewOrchestrator
- KeyURIPattern

Unexport:
- APIVersion
- TestKeyURI
- CloudKMSOperationalLatencies
- CloudKMSOperationalFailuresTotal
- RecordCloudKMSOperation
- RegisterMetrics
- Metrics/NewMetrics
- TokenConfig
- Validator/NewValidator

**Comment by immutableT** [comment]
Done.
