### ISSUE TITLE
simplify metrics registration

### ISSUE THREAD

**Issue by awly** [GoogleCloudPlatform/k8s-cloudkms-plugin#9]
Instead of `RegisterMetrics` with a `sync.Once`, just add
```
func init() {
  prometheus.MustRegister(CloudKMSOperationalLatencies)
  prometheus.MustRegister(CloudKMSOperationalFailuresTotal)
}
```
(you can have multiple init funcs btw).

**Comment by immutableT** [comment]
Question:
I do have this:
func init() {
	RegisterMetrics()
}
in plugin.go.

So, the suggestion is to use the init in metrics.go instead and to get rid of the sync.once, correct?

I also realized that I was not registering FailuresTotal - fixed.

**Comment by awly** [comment]
Yep, remove the intermediate (and exported) RegisterMetrics func and put init next to defined metrics.
sync.Once would be needed if you ever called the func multiple times.

**Comment by immutableT** [comment]
Done.
